In [2]:
import pandas as pd

In [3]:
# 2. CSV 파일들 로드
# df = pd.read_csv('./data/application_test.csv', encoding='utf-8-sig')
# df1 = pd.read_csv('./data/application_train.csv', encoding='utf-8-sig')
df2 = pd.read_csv('./data/bureau.csv', encoding='utf-8-sig')
# df3 = pd.read_csv('./data/bureau_balance.csv', encoding='utf-8-sig')
# df4 = pd.read_csv('./data/credit_card_balance.csv', encoding='utf-8-sig')
# df5 = pd.read_csv('./data/installments_payments.csv', encoding='utf-8-sig')
# df6 = pd.read_csv('./data/POS_CASH_balance.csv', encoding='utf-8-sig')
# df7 = pd.read_csv('./data/previous_application.csv', encoding='utf-8-sig')

In [4]:
df2

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,11250.00,11250.0,0.0,0.0,Microloan,-19,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,38130.84,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.00,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.00,0.0,0.0,0.0,Consumer credit,-1508,NaN
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.00,0.0,NaN,0.0,Microloan,-387,NaN

In [4]:
fact = df2['DAYS_ENDDATE_FACT']

In [5]:
fact.value_counts()

DAYS_ENDDATE_FACT
-329.0     811
-273.0     794
-301.0     791
-91.0      785
-84.0      783
          ...
-2905.0      1
-2898.0      1
-2900.0      1
-2922.0      1
-2891.0      1
Name: count, Length: 2917, dtype: int64

In [10]:
df2['DAYS_ENDDATE_FACT'].describe()

count    1.082775e+06
mean    -1.017437e+03
std      7.140106e+02
min     -4.202300e+04
25%     -1.489000e+03
50%     -8.970000e+02
75%     -4.250000e+02
max      0.000000e+00
Name: DAYS_ENDDATE_FACT, dtype: float64

In [11]:
df2['AMT_CREDIT_SUM'].describe()

count    1.716415e+06
mean     3.549946e+05
std      1.149811e+06
min      0.000000e+00
25%      5.130000e+04
50%      1.255185e+05
75%      3.150000e+05
max      5.850000e+08
Name: AMT_CREDIT_SUM, dtype: float64

In [12]:
cutoff = df2['AMT_CREDIT_SUM'].quantile(0.99)
cutoff

3700916.0999999824

In [ ]:
df_cutoff = df2[df2['AMT_CREDIT_SUM'] >= cutoff]
df_cutoff['AMT_CREDIT_SUM']

12         7033500.0
26         3709552.5
343        7794000.0
384        5355000.0
406        3996000.0
             ...
1715800    6300000.0
1715877    8262000.0
1715986    5395500.0
1716173    9720000.0
1716221    4081248.0
Name: AMT_CREDIT_SUM, Length: 17165, dtype: float64

In [18]:
df_cutoff['AMT_CREDIT_SUM'].describe()

count    1.716500e+04
mean     7.164020e+06
std      8.041165e+06
min      3.700935e+06
25%      4.500000e+06
50%      5.796000e+06
75%      7.956000e+06
max      5.850000e+08
Name: AMT_CREDIT_SUM, dtype: float64

In [ ]:
df_m = df2[df2['AMT_CREDIT_SUM_LIMIT'] < 0]

         SK_ID_CURR  AMT_CREDIT_SUM_LIMIT
1966         319729             -5779.440
7774         436084           -110293.605
17054        131849            -11413.260
17952        442762             -1352.385
20661        445702            -13834.305
...             ...                   ...
1710717      268964             -4539.375
1711841      280361             -7897.275
1712025      209751            -19425.240
1712577      218101             -3377.610
1715060      367213              -168.165

[351 rows x 2 columns]

In [32]:
m = df_m['AMT_CREDIT_SUM_LIMIT'].value_counts()
m

AMT_CREDIT_SUM_LIMIT
-5779.440      1
-18042.885     1
-71290.575     1
-5029.785      1
-57.870        1
              ..
-216620.010    1
-6804.180      1
-90878.805     1
-6202.665      1
-168.165       1
Name: count, Length: 351, dtype: int64

In [28]:
df6 = pd.read_csv('./data/POS_CASH_balance.csv', encoding='utf-8-sig')

In [30]:
df6['NAME_CONTRACT_STATUS'].value_counts()

NAME_CONTRACT_STATUS
Active                   9151119
Completed                 744883
Signed                     87260
Demand                      7065
Returned to the store       5461
Approved                    4917
Amortized debt               636
Canceled                      15
XNA                            2
Name: count, dtype: int64

In [36]:
df6['SK_DPD'].describe()

count    1.000136e+07
mean     1.160693e+01
std      1.327140e+02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      4.231000e+03
Name: SK_DPD, dtype: float64

In [39]:
df6[['SK_ID_CURR','CNT_INSTALMENT_FUTURE']]

          SK_ID_CURR  CNT_INSTALMENT_FUTURE
0             182943                   45.0
1             367990                   35.0
2             397406                    9.0
3             269225                   42.0
4             334279                   35.0
...              ...                    ...
10001353      226558                    0.0
10001354      141565                    0.0
10001355      315695                    0.0
10001356      450255                    0.0
10001357      174278                    0.0

[10001358 rows x 2 columns]

In [6]:
df2

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,11250.00,11250.0,0.0,0.0,Microloan,-19,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,38130.84,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.00,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.00,0.0,0.0,0.0,Consumer credit,-1508,NaN
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.00,0.0,NaN,0.0,Microloan,-387,NaN

In [5]:
df2['SK_ID_CURR'].value_counts()

SK_ID_CURR
120860    116
169704     94
318065     78
251643     61
425396     60
         ...
405288      1
413028      1
288569      1
215224      1
235871      1
Name: count, Length: 305811, dtype: int64

In [7]:
df2['SK_ID_BUREAU'].value_counts()

SK_ID_BUREAU
5714462    1
6758530    1
6758496    1
6758495    1
6758494    1
          ..
6298831    1
6298830    1
6298829    1
6298828    1
5057778    1
Name: count, Length: 1716428, dtype: int64

In [ ]:
def add_overlap_and_credit_increase_features(bureau):
    """
    bureau 데이터프레임에 아래 파생변수를 추가합니다:

    - OVERLAP: 기존 대출이 끝나기 전에 신규 대출을 받은 경우 (True/False)
    - CREDIT_INCREASED: 겹친 상태에서 대출 금액이 증가한 경우 (True/False)
    - DELTA_CREDIT_SUM_IF_INCREASED: 이전보다 대출 금액이 얼마나 증가했는지 (금액 차이)
    - DELTA_CREDIT_PCT_IF_INCREASED: 이전보다 대출 금액이 얼마나 증가했는지 (비율 %)
    - OVERLAP_DAYS: 겹쳐진 대출의 기간 (며칠 겹쳤는지)
    - OVERLAP_YEARS: 겹쳐진 대출의 기간 (연 단위)
    - CREDIT_TERM_DAYS: 각 대출의 전체 예정 기간 (일 단위)
    - CREDIT_TERM_YEARS: 각 대출의 전체 예정 기간 (연 단위)
    """
    bureau_sorted = bureau.copy()
    
    # 시작일, 종료일 (신청일 기준 상대적 일 수)
    bureau_sorted['START_DATE'] = bureau_sorted['DAYS_CREDIT']
    bureau_sorted['END_DATE'] = bureau_sorted['DAYS_CREDIT_ENDDATE']
    
    # 고객별로 대출 시작일 기준 정렬
    bureau_sorted = bureau_sorted.sort_values(['SK_ID_CURR', 'START_DATE'])
    
    # 이전 대출 종료일, 대출 금액
    bureau_sorted['PREV_END'] = bureau_sorted.groupby('SK_ID_CURR')['END_DATE'].shift()
    bureau_sorted['PREV_SUM'] = bureau_sorted.groupby('SK_ID_CURR')['AMT_CREDIT_SUM'].shift()
    # print(bureau_sorted['PREV_END'])
    # print(bureau_sorted['PREV_SUM'])
    
    # OVERLAP: 기존 대출이 끝나기 전에 신규 대출을 받은 경우
    bureau_sorted['OVERLAP'] = bureau_sorted['START_DATE'] < bureau_sorted['PREV_END']
    
    # CREDIT_INCREASED: 겹친 상태에서 대출 금액이 증가한 경우
    bureau_sorted['CREDIT_INCREASED'] = (
        bureau_sorted['OVERLAP'] & 
        (bureau_sorted['AMT_CREDIT_SUM'] > bureau_sorted['PREV_SUM'])
    )
    
    # DELTA_CREDIT_SUM_IF_INCREASED: 대출 금액 증가분 (금액 차이)
    bureau_sorted['DELTA_CREDIT_SUM_IF_INCREASED'] = bureau_sorted.apply(
        lambda row: row['AMT_CREDIT_SUM'] - row['PREV_SUM'] if row['CREDIT_INCREASED'] else None,
        axis=1
    )
    
    # DELTA_CREDIT_PCT_IF_INCREASED: 대출 금액 증가율 (%)
    bureau_sorted['DELTA_CREDIT_PCT_IF_INCREASED'] = bureau_sorted.apply(
        lambda row: (row['AMT_CREDIT_SUM'] - row['PREV_SUM']) / row['PREV_SUM']
        if row['CREDIT_INCREASED'] and row['PREV_SUM'] not in [0, None] else None,
        axis=1
    )
    
    # OVERLAP_DAYS: 대출 간 겹친 기간 (일 단위)
    bureau_sorted['OVERLAP_DAYS'] = bureau_sorted['PREV_END'] - bureau_sorted['START_DATE']
    
    # OVERLAP_YEARS: 대출 간 겹친 기간 (연 단위)
    bureau_sorted['OVERLAP_YEARS'] = bureau_sorted['OVERLAP_DAYS'] / 365
    
    # CREDIT_TERM_DAYS: 대출의 전체 예정 기간 (일 단위)
    bureau_sorted['CREDIT_TERM_DAYS'] = bureau_sorted['END_DATE'] - bureau_sorted['START_DATE']
    
    # CREDIT_TERM_YEARS: 대출의 전체 예정 기간 (연 단위)
    bureau_sorted['CREDIT_TERM_YEARS'] = bureau_sorted['CREDIT_TERM_DAYS'] / 365

    # 원본에 붙이기
    bureau = bureau.copy()
    cols_to_add = [
        'OVERLAP',
        'CREDIT_INCREASED',
        'DELTA_CREDIT_SUM_IF_INCREASED',
        'DELTA_CREDIT_PCT_IF_INCREASED',
        'OVERLAP_DAYS',
        'OVERLAP_YEARS',
        'CREDIT_TERM_DAYS',
        'CREDIT_TERM_YEARS',
    ]
    for col in cols_to_add:
        bureau[col] = bureau_sorted[col]

    return bureau

bureau = add_overlap_and_credit_increase_features(df2)

In [5]:
bureau

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,...,DAYS_CREDIT_UPDATE,AMT_ANNUITY,OVERLAP,CREDIT_INCREASED,DELTA_CREDIT_SUM_IF_INCREASED,DELTA_CREDIT_PCT_IF_INCREASED,OVERLAP_DAYS,OVERLAP_YEARS,CREDIT_TERM_DAYS,CREDIT_TERM_YEARS
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,...,-131,NaN,True,False,NaN,NaN,1694.0,4.641096,344.0,0.942466
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,...,-20,NaN,True,True,45000.0,0.25000,27668.0,75.802740,1283.0,3.515068
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,...,-16,NaN,True,True,239323.5,1.06366,1278.0,3.501370,731.0,2.002740
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,...,-16,NaN,True,False,NaN,NaN,731.0,2.002740,NaN,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,...,-21,NaN,False,False,NaN,NaN,-201.0,-0.550685,1826.0,5.002740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,...,-19,NaN,True,False,NaN,NaN,292.0,0.800000,14.0,0.038356
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,...,-2493,NaN,True,False,NaN,NaN,1024.0,2.805479,215.0,0.589041
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,...,-967,NaN,True,False,NaN,NaN,2469.0,6.764384,181.0,0.495890
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,...,-1508,NaN,False,False,NaN,NaN,-185.0,-0.506849,365.0,1.000000
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,...,-387,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
temp = bureau.copy()

In [12]:
# 시작일, 종료일 (신청일 기준 상대적 일 수)
temp['START_DATE'] = temp['DAYS_CREDIT']
temp['END_DATE'] = temp['DAYS_CREDIT_ENDDATE']

# 고객별로 대출 시작일 기준 정렬
temp = temp.sort_values(['SK_ID_CURR', 'START_DATE'])

# 이전 대출 종료일, 대출 금액
temp['PREV_END'] = temp.groupby('SK_ID_CURR')['END_DATE'].shift()
temp['PREV_SUM'] = temp.groupby('SK_ID_CURR')['AMT_CREDIT_SUM'].shift()

In [ ]:
temp['START_DATE']

count    1.716428e+06
mean    -1.142108e+03
std      7.951649e+02
min     -2.922000e+03
25%     -1.666000e+03
50%     -9.870000e+02
75%     -4.740000e+02
max      0.000000e+00
Name: START_DATE, dtype: float64

In [21]:
temp.groupby('SK_ID_CURR')['END_DATE'].head()

248487    -1329.0
248485     -179.0
248486     -514.0
248484     -492.0
248488      902.0
            ...
1010012    8620.0
1010013   -1243.0
1010011     315.0
1010003    -959.0
1010006    -959.0
Name: END_DATE, Length: 1130840, dtype: float64

In [22]:
temp.groupby('SK_ID_CURR')['AMT_CREDIT_SUM'].head()

248487      85500.0
248485     279720.0
248486      91620.0
248484     112500.0
248488     337680.0
             ...
1010012     38925.0
1010013    450000.0
1010011    900000.0
1010003     22995.0
1010006     22995.0
Name: AMT_CREDIT_SUM, Length: 1130840, dtype: float64

In [16]:
cols = [
    'SK_ID_CURR',
    'AMT_CREDIT_SUM',
    'DAYS_CREDIT',
    'DAYS_CREDIT_ENDDATE',
    'START_DATE',
    'END_DATE',
    'PREV_END',
    'PREV_SUM'
]

temp[cols]

,SK_ID_CURR,AMT_CREDIT_SUM,DAYS_CREDIT,DAYS_CREDIT_ENDDATE,START_DATE,END_DATE,PREV_END,PREV_SUM
248487,100001,85500.0,-1572,-1329.0,-1572,-1329.0,NaN,NaN
248485,100001,279720.0,-909,-179.0,-909,-179.0,-1329.0,85500.0
248486,100001,91620.0,-879,-514.0,-879,-514.0,-179.0,279720.0
248484,100001,112500.0,-857,-492.0,-857,-492.0,-514.0,91620.0
248488,100001,337680.0,-559,902.0,-559,902.0,-492.0,112500.0
...,...,...,...,...,...,...,...,...
1010004,456255,27472.5,-970,-621.0,-970,-621.0,806.0,810000.0
1010005,456255,553500.0,-573,523.0,-573,523.0,-621.0,27472.5
1010010,456255,450000.0,-451,279.0,-451,279.0,523.0,553500.0
1010008,456255,90000.0,-378,27320.0,-378,27320.0,279.0,450000.0
1010009,456255,436032.0,-363,1463.0,-363,1463.0,27320.0,90000.0

In [32]:
def add_overlap_and_credit_increase_features(bureau):
    bureau_sorted = bureau.copy()
    
    """
    bureau 데이터프레임에 아래 파생변수를 추가합니다:
    
    - IS_FIRST_LOAN: 해당 고객의 첫 번째 대출인지 여부 (True/False)
    - IS_ONGOING: 종료일이 없어 현재 진행 중인 대출인지 여부 (True/False)
    - OVERLAP: 기존 대출이 끝나기 전에 신규 대출을 받은 경우 (True/False)
    - CREDIT_INCREASED: 겹친 상태에서 대출 금액이 증가한 경우 (True/False)
    - DELTA_CREDIT_SUM_IF_INCREASED: 이전보다 대출 금액이 얼마나 증가했는지 (금액 차이)
    - DELTA_CREDIT_PCT_IF_INCREASED: 이전보다 대출 금액이 얼마나 증가했는지 (비율 %)
    - OVERLAP_DAYS: 겹쳐진 대출의 기간 (며칠 겹쳤는지)
    - OVERLAP_YEARS: 겹쳐진 대출의 기간 (연 단위)
    - CREDIT_TERM_DAYS: 각 대출의 전체 예정 기간 (일 단위)
    - CREDIT_TERM_YEARS: 각 대출의 전체 예정 기간 (연 단위)
    """

    # 시작일, 종료일
    bureau_sorted['START_DATE'] = bureau_sorted['DAYS_CREDIT']
    bureau_sorted['END_DATE'] = bureau_sorted['DAYS_CREDIT_ENDDATE']

    # 고객별 정렬
    bureau_sorted = bureau_sorted.sort_values(['SK_ID_CURR', 'START_DATE'])

    # 이전 대출 정보
    bureau_sorted['PREV_END'] = bureau_sorted.groupby('SK_ID_CURR')['END_DATE'].shift()
    bureau_sorted['PREV_SUM'] = bureau_sorted.groupby('SK_ID_CURR')['AMT_CREDIT_SUM'].shift()

    # 첫 번째 대출 여부
    bureau_sorted['IS_FIRST_LOAN'] = bureau_sorted['PREV_END'].isna()

    # 진행 중인 대출 여부 (종료일 없음)
    bureau_sorted['IS_ONGOING'] = bureau_sorted['END_DATE'].isna()

    # 겹침 여부
    bureau_sorted['OVERLAP'] = bureau_sorted['START_DATE'] < bureau_sorted['PREV_END']

    # 대출 금액 증가 여부
    bureau_sorted['CREDIT_INCREASED'] = (
        bureau_sorted['OVERLAP'] &
        (bureau_sorted['AMT_CREDIT_SUM'] > bureau_sorted['PREV_SUM'])
    )

    # 증가분
    bureau_sorted['DELTA_CREDIT_SUM_IF_INCREASED'] = bureau_sorted.apply(
        lambda row: row['AMT_CREDIT_SUM'] - row['PREV_SUM']
        if row['CREDIT_INCREASED'] else None,
        axis=1
    )

    bureau_sorted['DELTA_CREDIT_PCT_IF_INCREASED'] = bureau_sorted.apply(
        lambda row: (row['AMT_CREDIT_SUM'] - row['PREV_SUM']) / row['PREV_SUM']
        if row['CREDIT_INCREASED'] and row['PREV_SUM'] not in [0, None] else None,
        axis=1
    )

    # 겹친 기간
    bureau_sorted['OVERLAP_DAYS'] = bureau_sorted['PREV_END'] - bureau_sorted['START_DATE']
    bureau_sorted['OVERLAP_YEARS'] = bureau_sorted['OVERLAP_DAYS'] / 365

    # 대출 기간
    bureau_sorted['CREDIT_TERM_DAYS'] = bureau_sorted['END_DATE'] - bureau_sorted['START_DATE']
    bureau_sorted['CREDIT_TERM_YEARS'] = bureau_sorted['CREDIT_TERM_DAYS'] / 365

    # 원본에 붙이기
    bureau = bureau.copy()
    cols_to_add = [
        'IS_FIRST_LOAN',
        'IS_ONGOING',
        'OVERLAP',
        'CREDIT_INCREASED',
        'DELTA_CREDIT_SUM_IF_INCREASED',
        'DELTA_CREDIT_PCT_IF_INCREASED',
        'OVERLAP_DAYS',
        'OVERLAP_YEARS',
        'CREDIT_TERM_DAYS',
        'CREDIT_TERM_YEARS',
    ]
    print("추가 컬럼 생성 여부:", [c for c in ['IS_FIRST_LOAN','IS_ONGOING'] if c in bureau_sorted.columns])

    for col in cols_to_add:
        bureau[col] = bureau_sorted[col]

    return bureau

bureau = add_overlap_and_credit_increase_features(df2)

추가 컬럼 생성 여부: ['IS_FIRST_LOAN', 'IS_ONGOING']

In [34]:
bureau

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,...,IS_FIRST_LOAN,IS_ONGOING,OVERLAP,CREDIT_INCREASED,DELTA_CREDIT_SUM_IF_INCREASED,DELTA_CREDIT_PCT_IF_INCREASED,OVERLAP_DAYS,OVERLAP_YEARS,CREDIT_TERM_DAYS,CREDIT_TERM_YEARS
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,...,False,False,True,False,NaN,NaN,1694.0,4.641096,344.0,0.942466
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,...,False,False,True,True,45000.0,0.25000,27668.0,75.802740,1283.0,3.515068
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,...,False,False,True,True,239323.5,1.06366,1278.0,3.501370,731.0,2.002740
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,...,False,True,True,False,NaN,NaN,731.0,2.002740,NaN,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,...,False,False,False,False,NaN,NaN,-201.0,-0.550685,1826.0,5.002740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,...,False,False,True,False,NaN,NaN,292.0,0.800000,14.0,0.038356
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,...,False,False,True,False,NaN,NaN,1024.0,2.805479,215.0,0.589041
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,...,False,False,True,False,NaN,NaN,2469.0,6.764384,181.0,0.495890
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,...,False,False,False,False,NaN,NaN,-185.0,-0.506849,365.0,1.000000
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,...,True,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
app = pd.read_csv("./data/application_train.csv")

# bureau에 기록이 있는지 여부
app['HAS_BUREAU_HISTORY'] = app['SK_ID_CURR'].isin(bureau['SK_ID_CURR'])

# 기록이 없는 고객
no_history = app[~app['HAS_BUREAU_HISTORY']]

In [40]:
print(app['HAS_BUREAU_HISTORY'].value_counts())

HAS_BUREAU_HISTORY
True     263491
False     44020
Name: count, dtype: int64

In [42]:
app

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,HAS_BUREAU_HISTORY
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,True
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,True
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,True
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,False
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,False
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,False
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,True
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,True
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,True

In [4]:
# 진행 중 대출 추정 플래그 (미래 종료 예정 + 실제 종료 안 됨)
df2["IS_ACTIVE_ESTIMATED"] = (
    (df2["DAYS_CREDIT_ENDDATE"] > 0) & 
    (df2["DAYS_ENDDATE_FACT"].isna())
).astype(int)

# 보너스: 실제 종료 여부 플래그
df2["IS_CLOSED_ACTUAL"] = df2["DAYS_ENDDATE_FACT"].notna().astype(int)

In [19]:
df2_active_agg = df2.groupby("SK_ID_CURR").agg({
    "IS_ACTIVE_ESTIMATED": "sum",       # 진행 중 대출 수
    "IS_CLOSED_ACTUAL": "mean",         # 종료된 대출 비율
    "DAYS_CREDIT_ENDDATE": "mean",      # 평균 만기일
    "DAYS_ENDDATE_FACT": lambda x: x.notna().mean(),  # 종료 비율 (중복)
}).reset_index()

In [20]:
df2_active_agg.columns = ["SK_ID_CURR"] + [f"bureau_{col}" for col in df2_active_agg.columns[1:]]
df2_active_agg["bureau_DAYS_CREDIT_ENDDATE"] = df2_active_agg["bureau_DAYS_CREDIT_ENDDATE"].round(0).astype("Int64")
df2_active_agg["bureau_DAYS_ENDDATE_FACT"] = df2_active_agg["bureau_DAYS_ENDDATE_FACT"].round(3)

In [23]:
df2_active_agg

,SK_ID_CURR,bureau_IS_ACTIVE_ESTIMATED,bureau_IS_CLOSED_ACTUAL,bureau_DAYS_CREDIT_ENDDATE,bureau_DAYS_ENDDATE_FACT
0,100001,3,0.571429,82,0.571
1,100002,1,0.750000,-349,0.750
2,100003,1,0.750000,-544,0.750
3,100004,0,1.000000,-488,1.000
4,100005,2,0.333333,439,0.333
...,...,...,...,...,...
305806,456249,1,0.923077,-1232,0.923
305807,456250,2,0.333333,1288,0.333
305808,456253,2,0.500000,280,0.500
305809,456254,0,1.000000,-859,1.000
305810,456255,5,0.545455,3231,0.545

In [25]:
df2_active_agg.to_csv('df2_active_agg.csv', index=False, encoding='utf-8-sig')